sitegeist/Sitegeist.Kaleidoscope

- Classes/Controller/DummyImageController.php
- Classes/EelHelpers/DummyImageSourceHelper.php
- Classes/FusionObjects/DummyImageSourceImplementation.php
- Configuration/Objects.yaml
- Configuration/Policy.yaml
- Configuration/Routes.yaml
- Configuration/Settings.yaml
- README.md
- composer.json
This replaces dummyimage.com with a custom dmmyimage controller to enable local testing without 
external dependencies.
The implementation is based on the imagine library and renders a mountain-shape similar to the
default dummy image of neos in the created dummy.
> Feature: Integrate custom dummy image service

- Classes/Controller/DummyImageController.php
The gd method imagesetthickness seems not to work in all cases.
This change alters the drawing of the border to a loop of 1px lines
to deal with this.
Additionally the border is now always 10px + 10px wide.
> TASK: Render border with GD

- Classes/FusionObjects/AssetImageSourceImplementation.php
- Classes/FusionObjects/DummyImageSourceImplementation.php
- Classes/FusionObjects/UriImageSourceImplementation.php
The AssetImageSource will create an UriImageSourceHelper if an svg image was selected.
> BUGFIX: Add fallback to UriImageSourceHelper for SVG images

- Classes/EelHelpers/AbstractImageSourceHelper.php
When an image is not found due to security constraints, an exception is thrown
which is covered by PHPs exception that __toString should never throw an exception.
> BUGFIX: __toString must not throw an exception

- Classes/EelHelpers/AbstractImageSourceHelper.php
- Classes/EelHelpers/AbstractScalableImageSourceHelper.php
- Classes/EelHelpers/AssetImageSourceHelper.php
- Classes/EelHelpers/DummyImageSourceHelper.php
- Classes/EelHelpers/ImageSourceHelperInterface.php
- Classes/EelHelpers/UriImageSourceHelper.php
- README.md
* `setDimensions` allows to set width and height at once
* `preserveAspect` on `setWidth` and `setHeight` will make sure the current aspect of the image as defined by base/target width  and height is perserved during the operation
> FEATURE: add `setDimensions` to imageSourceInterface and add second `preserveAspect` argument to `setWidth` and `setHeight`

- Classes/Controller/DummyImageController.php
This change uses the multiplicator sign `×` instead of ` x `. A further benefit that we can save two spaces.
> FEATURE: Use × instead of x

- README.md
- Resources/Private/Fusion/Prototypes/Image.fusion
- Resources/Private/Fusion/Prototypes/Picture.fusion
- Resources/Private/Fusion/Prototypes/Source.fusion
- `renderDimensionAttributes`: render dimension attributes (width/height) when the data is available from the imageSource. Enabled by default
- `loading`: (optional) loading attribute for the img tag 
- `width`: (optional) the base width, will be applied to the `imageSource`
- `height`: (optional) the base height, will be applied to the `imageSource`   
- `format`: (optional) the image-format like `webp` or `png`, is applied to the `imageSource`
- `renderDimensionAttributes`: render dimension attributes (width/height) for the img-tag when the data is available from the imageSource
if not specified dimensions will be enabled automatically for pictures that only use the `formats` options.
- `formats`: (optional) image formats that will be rendered as sources of separate type (string or …
> !!! FEATURE: Add props `renderDimensionAttributes`, `width`, `height`, `loading` and `format` resp. `formats`

- README.md
The README.md has a small typo in the "Picture with multiple sources:" example. This can result in a "Prop-assignment was not followed by quotes or braces" error if some one do copy/paste.
And i moved the webp example to top. Because of browsers reading order from top to down and using the first match.
> BUGFIX: Update prop-assignment in README.md

- Classes/EelHelpers/AbstractImageSourceHelper.php
- Classes/EelHelpers/ImageSourceHelperInterface.php
- Classes/FusionObjects/AbstractImageSourceImplementation.php
- Classes/FusionObjects/AssetImageSourceImplementation.php
- Classes/FusionObjects/DummyImageSourceImplementation.php
- Classes/FusionObjects/ResourceImageSourceImplementation.php
- Classes/FusionObjects/UriImageSourceImplementation.php
- README.md
- Resources/Private/Fusion/Prototypes/Image.fusion
All imageSource FusionObjects now support the fusion attributes 'alt' and 'title' that will be used as fallback for the
respective attributes of the img-tag. That way it is no longer necessary to pass three separate properties around.
Examples:
1. Use title and alternativeText from node properties with fallback to the asset title:
```
imageSource = Sitegeist.Kaleidoscope:AssetImageSource {
asset = ${q(node).property('image')}
title =  ${q(node).property('title') || q(node).property('image').title}
alt = ${q(node).property('alternativeText')}
}
```
2. Set alt and title for dummy image source
```
imageSource = Sitegeist.Kaleidoscope:DummyImageSource {
alt = 'Alternate assigned to source'
title = 'Title assigned to source'
}
```
> FEATURE: Generic alt and title support

- Resources/Private/Fusion/Prototypes/Source.fusion
see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source
> BUGFIX: Remove src attributes from source tag that is technically allowed but ignored inside of picture elements

- README.md
- Resources/Private/Fusion/Prototypes/Picture.fusion
- Resources/Private/Fusion/Prototypes/Source.fusion
This is controlled by the property. renderDimensionAttributes which is enabled by default.
> FEATURE: Render width and height for Picture Sources to prevent layout shifts.

- README.md
- Resources/Private/Fusion/Prototypes/Image.fusion
- Resources/Private/Fusion/Prototypes/Picture.fusion
The `attributes` property of `Sitegeist.Kaleidoscope:Image` and `Sitegeist.Kaleidoscope:Picture` allows to add additional attributes or to override existing ones. To control the attributes of the img tag inside of picture `imgAttributes`
```
imageSource = Sitegeist.Kaleidoscope:DummyImageSource
renderer = afx`
<Sitegeist.Kaleidoscope:Image
imageSource={props.imageSource}
attributes.style="border: 5px solid pink;" 
attributes.data-example="foo"        
/>
<Sitegeist.Kaleidoscope:Picture
imageSource={props.imageSource}
attributes.data-example="picture-data"        
imgAttributes.style="border: 5px solid pink;" 
imgAttributes.data-example="img-data" 
/>
`
```
Resolves: #51
> FEATURE: Add generic attributes support

- Resources/Private/Fusion/Prototypes/Picture.fusion
Apply width and height constraints defined for the main element to the items when the formats option is used to render multiple formats in Sitegeist.Kaleidoscope:Picture
> BUGFIX: Apply `width` and `height` for `Sitegeist.Kaleidoscope:Picture` with `formats`

- .github/workflows/build.yml
- Classes/Controller/DummyImageController.php
- Classes/Domain/AbstractImageSource.php
- Classes/Domain/AbstractScalableImageSource.php
- Classes/Domain/AssetImageSource.php
- Classes/Domain/DummyImageGenerator.php
- Classes/Domain/DummyImageSource.php
- Classes/Domain/ImageSourceInterface.php
- Classes/Domain/ResourceImageSource.php
- Classes/Domain/UriImageSource.php
- composer.json
This allows to render images with a data src to avoid a separate request. The dataSrc is generated synchronously which may cause performance issues.
To achieve this the generation of dummy images was extracted into the DummyImageGenerator for beeing able to crate synchonous dummy images.
Also the test matrix was adjusted to include recent and upcoming php and Neos versions 
and removes support of outdated Neos versions.
> FEATURE: Add dataSrc method to image source interface

- Resources/Private/Fusion/Prototypes/Image.fusion
- Resources/Private/Fusion/Prototypes/Source.fusion
Since size attribues for non scalable sources like svg files are pointless they should be avoided. 
This change ensures that only scalable imageSources will render size and srcset.
> FEATURE: Omit srcset and sizes if imageSource is non-scalable

- Classes/Domain/AbstractScalableImageSource.php
Use targetWidth and targetHeight for aspect ratio calculation when both are set. Otherwise this leads to unwanted results. We observed this behaviour with `srcset` and `1x, 2x` and `imageSource.withHeight(40, true)`
> BUGFIX: Respect aspect ratio

- Resources/Private/Fusion/Prototypes/Source.fusion
This fixes non-scalable images with different type sources. Currently, these images sources are empty.
Fixes #68
> BUGFIX: Output srcset in Source.fusion

- Resources/Private/Fusion/Prototypes/DummyImageSource.fusion
- Resources/Private/Fusion/Prototypes/Picture.fusion
Relates: neos/neos-development-collection#4537
> BUGFIX: Remove usage of deprecated fusion prototypes

- Classes/Domain/AbstractImageSource.php
- Classes/Domain/AssetImageSource.php
- Classes/Domain/ImageSourceInterface.php
- Classes/EelHelpers/ImageSourceHelperInterface.php
- Classes/FusionObjects/AbstractImageSourceImplementation.php
- README.md
- Resources/Private/Fusion/Prototypes/AssetImageSource.fusion
- Resources/Private/Fusion/Prototypes/Image.fusion
- Resources/Private/Fusion/Prototypes/Picture.fusion
- Resources/Private/Fusion/Prototypes/Source.fusion
Closes #74
Setting this option can give a huge performance boost on websites, specially if you use large images
> FEATURE: Add quality option

- Classes/Domain/DummyImageSource.php
The base uri is for the dummy image controller is created internally if not given from the outside.
This makes creating those image sources programmatically much easier.
> TASK: Make BaseUri argument nullable in DummyImageSource constructor

- .editorconfig
- .github/workflows/build.yml
- Resources/Private/Fusion/Prototypes/Image.fusion
- Resources/Private/Fusion/Prototypes/Picture.fusion
- Resources/Private/Fusion/Prototypes/Source.fusion
- composer.json
This required Neos 8.3 + but should improve the performance as a level of fusion objects is avoided.
> TASK: Use @private instead of nested components

- Classes/Domain/DummyImageSource.php
Dummy images rendered wrong urls that prevented the url-parameters from beeing interpreted correctly.
> BUGFIX: Build correct dummy image urls again
